include: "https://gitlab.com/pipeline-templates/gitlab-ci-templates/-/raw/main/ansible/deploy/1.0.0-gitlab-ci.yml"

# Never run as this is a template. Override this in the implementation
workflow:
  rules:
    - when: never

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  TF_STATE_NAME: gitlab-wireguard-runner
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/$TF_STATE_NAME
  TF_VAR_SSH_PUBLIC_KEY: $SSH_PUBLIC_KEY
  TF_ADDRESS: YOUR_PROJECT_HERE
  GIT_SUBMODULE_STRATEGY: recursive
  WIREGUARD_CONFIG_DIRECTORY: $CI_PROJECT_DIR/wireguard-configs

image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

cache:
  key: $TF_STATE_NAME
  paths:
      - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}

stages:
  - prepare
  - validate
  - build
  - deploy
  - ansible
  - schedule_pipeline
  - destroy

prepare:
  stage: terraform
  script:
    - gitlab-terraform init
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

validate:
  stage: validate
  script:
    - gitlab-terraform validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

plan:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

apply:
  stage: deploy
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  artifacts:
    paths:
      - ${TF_ROOT}/instance_ips.ini
    expire_in: 1 hour
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

# Uses template file as template
ansible_deploy:
  stage: ansible
  variables:
    ANSIBLE_INVENTORY: ${TF_ROOT}/instance_ips.ini
  dependencies: 
    - create
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

schedule-destroy:
  variables:
    TIMEZONE: UTC
  stage: schedule_pipeline
  image: dwdraju/alpine-curl-jq
  script: 
    - ${CI_PROJECT_DIR}/destroy-scheduler/schedule_destroy.sh
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

destroy:
  stage: destroy
  script:
    - gitlab-terraform destroy
    - ${CI_PROJECT_DIR}/destroy-scheduler/remove_all_scheduled_destroys.sh
  dependencies:
    - create
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: manual

