---
- name: (Debian) Get Gitlab repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: /tmp/gitlab-runner.script.deb.sh
    mode: 0744

- name: (Debian) Install Gitlab repository
  command: bash /tmp/gitlab-runner.script.deb.sh
  args:
    creates: "/etc/apt/sources.list.d/runner_gitlab-runner.list"

- name: Install GitLab Runner
  apt:
    name: gitlab-runner
    state: latest
    update_cache: yes

- name: Register gitlab-runner
  command: gitlab-runner register >
    --non-interactive \
    --url "{{ gitlab_url }}" \
    --registration-token "{{ gitlab_runner_registration_token }}" \
    --executor "{{ gitlab_runner_executor }}" \
    --docker-image {{ gitlab_runner_default_docker_image }} \
    --description "{{ gitlab_runner_description }}" \
    --tag-list "{{ gitlab_runner_tags }}" \
    --run-untagged="{{ gitlab_runner_untagged_builds_run }}" \
    --locked="{{ gitlab_runner_lock_to_project }}" \
    --access-level="{{ gitlab_runner_access_level }}"
